import assert from "node:assert/strict"
import test from "node:test"
import { buildProductPayload, createEmptyProductForm, getGrossMargin, getProductFormErrors, getTotalVariantStock, normalizeVariantsForCategory, slugifyProductName, validateProductForm, type ProductFormCategory } from "../lib/product-form"

const category: ProductFormCategory = { id: "category", name: "Camisetas", slug: "camisetas", supportsSize: true, supportsColor: true, supportsFlavor: false, supportsWeight: false, trackStockByVariant: true, trackExpiration: false, parent: { id: "parent", name: "Roupas", slug: "roupas-fitness" } }

test("creates product and variant defaults", () => { const form = createEmptyProductForm(); assert.equal(form.active, true); assert.equal(form.isNew, true); assert.equal(form.variants.length, 1) })
test("generates normalized slugs", () => assert.equal(slugifyProductName("  Camiseta Edição Verão!  "), "camiseta-edicao-verao"))
test("normalizes irrelevant category attributes and collapses stock", () => { const next = normalizeVariantsForCategory([{ ...createEmptyProductForm().variants[0], size: "M", color: "Preto", stock: "3" }, { ...createEmptyProductForm().variants[0], stock: "4" }], { ...category, supportsSize: false, supportsColor: false, trackStockByVariant: false }); assert.equal(next.length, 1); assert.equal(next[0].stock, "7"); assert.equal(next[0].size, "") })
test("validates required product and variant fields", () => { const form = { ...createEmptyProductForm(), name: "Produto", price: "R$ 10,00", costPrice: "R$ 5,00", categoryId: category.id }; assert.match(validateProductForm(form, category) ?? "", /tamanho/); assert.equal(validateProductForm({ ...form, variants: [{ ...form.variants[0], size: "M", color: "Preto" }] }, category), null) })
test("maps validation errors to the rendered field ids", () => { const errors = getProductFormErrors(createEmptyProductForm(), category); assert.equal(errors["product-name"], "Informe o nome do produto."); assert.equal(errors["product-price"], "Informe o preço de venda."); assert.equal(errors["variant-size-0"], "Informe o tamanho da variante 1.") })
test("calculates total stock and gross margin", () => { assert.equal(getTotalVariantStock([{ ...createEmptyProductForm().variants[0], stock: "2" }, { ...createEmptyProductForm().variants[0], stock: "5" }]), 7); assert.equal(getGrossMargin("R$ 100,00", "R$ 60,00"), 40) })
test("builds the existing API payload semantics", () => { const form = { ...createEmptyProductForm(), name: " Camiseta ", price: "R$ 100,00", costPrice: "R$ 60,00", categoryId: category.id, gender: "unissex", variants: [{ ...createEmptyProductForm().variants[0], size: "M", color: "Preto", stock: "8" }] }; const payload = buildProductPayload(form, category); assert.equal(payload.slug, "camiseta"); assert.equal(payload.price, 100); assert.equal(payload.costPrice, 60); assert.equal(payload.gender, "unissex"); assert.equal(payload.variants[0].stock, 8); assert.equal(payload.variants[0].flavor, null) })
